#
# Makefile for Counter devices
#

# When adding new entries keep the list in alphabetical order

obj-$(CONFIG_COUNTER) += counter.o
counter-y := generic-counter.o

obj-$(CONFIG_104_QUAD_8)	+= 104-quad-8.o
obj-$(CONFIG_STM32_TIMER_CNT) += stm32-timer-cnt.o
obj-$(CONFIG_STM32_LPTIMER_CNT)	+= stm32-lptimer-cnt.o
